---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trackszdevsinelo/public_html/
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        - /bin/cp -R app $DEPLOYPATH
        - /bin/cp -R bootstrap $DEPLOYPATH
        - /bin/cp -R config $DEPLOYPATH
        - /bin/cp -R public $DEPLOYPATH
        - /bin/cp -R resources $DEPLOYPATH
